# Generated by Django 5.2.10 on 2026-01-28 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 6, 51, 7, 129276, tzinfo=datetime.timezone.utc)),
        ),
    ]
