# Generated by Django 5.2.10 on 2026-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title_field',
            field=models.CharField(blank=True, default='Untitled', max_length=255, null=True),
        ),
    ]
